version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - gocyclo
    - gocognit
    - nestif
    - errorlint
    - errname
    - goconst
    - godot
    - nakedret
    - prealloc
    - makezero
    - noctx
    - gosec
    - testifylint
    - tparallel
    - thelper
    - usestdlibvars
    - perfsprint

  disable:
    - wsl
    - lll
    - gochecknoglobals
    - gochecknoinits

linters-settings:
  gocyclo:
    min-complexity: 15
  nestif:
    min-complexity: 5
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - hugeParam

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0